spring.application.name=inventory
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=postgres
spring.datasource.password=Baxtiyor123

spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=admin
spring.security.user.password=admin

spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.port=9091
file.upload-dir=uploads